version: '3'

services:
  postgres:
    image: postgres:13.2-alpine
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $TYPEORM_PASSWORD
      POSTGRES_USER: $TYPEORM_USERNAME
      POSTGRES_DB: $TYPEORM_DATABASE
      POSTGRES_HOST: $TYPEORM_HOST
    ports:
      - 5432:5432
    expose:
      - 5432
